spring.application.name=rapchieuphim

# 1. KẾT NỐI DATABASE (Đã thêm tham số cho phép lấy Public Key)
spring.datasource.url=jdbc:postgresql://dpg-xxxx:5432/cinebook_dbcinebook_db_veqe
spring.datasource.username=cinebook_db_veqe_user
spring.datasource.password=n7TI7gs6UOKYvTUKQVfq7eFHwAlz9JcI
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CẤU HÌNH JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# 3. LOGGING
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect